# Generated by Django 4.2.4 on 2023-09-17 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_alter_asset_owner_alter_liability_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(default='Stock', max_length=28)),
                ('date_obtained', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('symbol', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='liability',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Liability',
        ),
    ]
