# Generated by Django 4.2.4 on 2023-09-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_stock_remove_liability_owner_delete_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
