# Generated by Django 4.2.4 on 2023-09-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='value',
            new_name='price',
        ),
    ]
